#!/system/xbin/bash
# miniscript v1.0
#Ngapain lhu
#gk boleh ngerecode
#kecuali kesini buat belajar atau sebagai contoh
#Hargai authornya
#setelah sampai sini mau ngapain?
#anjing yang recode
# Variables
#blue= '\033[34;1m'
#green= '\033[32;1m'
#purple= '\033[35;1m'
#cyan= '\033[36;1m'
#red= '\033[31;1m'
#white= '\033[37;1m'                              
#yellow= '\033[33;1m'
clear
sleep 1
echo '\033[33;1mselamat datang di TooLs saya'
echo 'created by : Mr.Boy' | lolcat
echo '\033[35;1mgunakan dengan bijak +_+'
sleep 4
clear
echo  "####################################################" | lolcat
figlet  "Mr.Boy 65" | lolcat
echo "<===================================================>" | lolcat
echo  "█████████   ●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬●"
echo  "█▄█████▄█ __--╔╦═╦╗╔═╗╔╗─╔═╗╔═╗╔═╦═╗╔═╗"
echo  "█ ▼▼▼▼▼_---_--║║║║║║╦╝║║─║╔╝║║║║║║║║║╦╝"
echo  "█   --_-- --_ ║║║║║║╩╗║╚╗║╚╗║║║║║║║║║╩╗"
echo  "█ ▲▲▲▲▲ -_-- -╚═╩═╝╚═╝╚═╝╚═╝╚═╝╚╩═╩╝╚═╝"
echo  "█████████      «°°°°°°°°°°✧°°°°°°°°°°»"
echo  " ██ ██"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | lolcat
echo  '[$]' "TYPE TOOLS : kumpulan script termux" | lolcat
echo  '[$]' "Author     : Mr.Boy65" | lolcat
echo  '[$]' "Profile    : https://github.com/An4smultazam56" | lolcat
echo  '[$]' "version    : 1.0" | lolcat
echo  '[$]' "WA Author  : 081326043097" | lolcat
echo  '[$]' "Δ⃟̅Δ⃟̅Δ⃟̅Δ⃟̅Δ̅⃟Δ⃟̅Δ⃟̅Δ̅⃟Δ̅⃟Δ⃟̅Δ̅⃟Δ̅̅⃟Δ⃟̅Δ⃟̅Δ̅⃟Δ⃟⃟⃟⃟⃟⃟⃟⃟⃟⃟⃟⃟Δ⃟̅Δ⃟̅Δ⃟̅Δ⃟̅Δ̅⃟Δ⃟̅⃟Δ⃟̅Δ̅⃟Δ̅⃟Δ⃟̅Δ̅⃟Δ̅̅⃟Δ⃟̅Δ⃟̅Δ̅⃟Δ⃟⃟⃟⃟⃟⃟⃟⃟⃟⃟⃟⃟Δ⃟̅Δ⃟̅Δ⃟̅Δ" | lolcat
echo  "<-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=->" | lolcat
echo 'Pilihan Tools nya, silahkan ketik nomor saja ^_^' | lolcat
echo '[+] silahkan pilih toolsnya [+]' | lolcat
echo '[00]## Untuk Keluar dari script ##' | lolcat
sleep 1
echo  '<======================>' | lolcat
echo  '\033[32;1m[01] Mr.Rv1.1'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[35;1m[02] D-Tect'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[36;1m[03] CRACK PASSWORD HASH'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[31;1m[04] Dark FB VIP-PRO'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[37;1m[05] DDOS'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[33;1m[06] Lacak Lokasi IP'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[34;1m[07] Crack FB'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[35;1m[08] Hash-Buster'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[37;1m[09] H4CK CCTV v1'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[31;1m[10] T-FF'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[32;1m[11] B4J1N64N'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[33;1m[12] Torshammer'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[34;1m[13] Tembak XL'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[37;1m[14] TU4N B4DUTv4'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[36;1m[15] Hack FB Masal'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[33;1m[16] TUANB4DUTv3'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[38;1m[17] MBF'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[31;1m[18] Trojans'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[32;1m[19] Spam WA Tokped'
echo  '<======================>' | lolcat
sleep 1
echo  '\033[35;1m[20] Install Bahan Cvk :)'
echo '___________¥¥¥¥¥¥___________' | lolcat
sleep 1
echo "silahkan cvk pilih mana aja" | lolcat
echo '#semoga bermanfaat!!#' | lolcat
echo '\033[33;1m'
read -p '[#]Mr.Boy65: +~>' pilihan


if [ $pilihan = '01' ] || [ $pilihan = '1' ]
then
git clone https://github.com/Mr-R225/Mr.Rv1.1
cd Mr.Rv1.1
sh Mr.Rv1.1.sh
fi

if [ $pilihan = '02' ] || [ $pilihan = '2' ]
then
git clone https://github.com/shawarkhanethicalhacker/D-TECT
cd D-TECT
chmod +x d-tect.py
python2 d-tect.py
fi

if [ $pilihan = '03' ] || [ $pilihan = '3' ]
then
git clone https://github.com/FajriHidayat088/FHX-Hash-Killer/
cd FHX-Hash-Killer
python2 FHXHashKiller.py
fi

if [ $pilihan = '04' ] || [ $pilihan = '4' ]
then
git clone https://github.com/m4rche3ll-cyber/dark-vpro
cd dark-vpro
python2 dark-vpro.py
fi

if [ $pilihan = '05' ] || [ $pilihan = '5' ]
then
clear
git clone https://github.com/cyweb/hammer
cd hammer
python hammer.py
fi

if [ $pilihan = '06' ] || [ $pilihan = '6' ]
then
git clone https://github.com/maldevel/IPGeolocation
cd IPGeolocation
python ipgeolocation.py
fi

if [ $pilihan = '07' ] || [ $pilihan = '7' ]
then
git clone https://github.com/IqbalDev/multi_dev
cd multi_dev
python2 multi_dev.py
fi

if [ $pilihan = '08' ] || [ $pilihan = '8' ]
then
git clone https://github.com/UltimateHackers/Hash-Buster
cd Hash-Buster
python2 hash.py
fi

if [ $pilihan = '09' ] || [ $pilihan = '9' ]
then
git clone https://github.com/GUNAWAN18ID/cctv.git
cd cctv
python2 scanner.py
fi

if [ $pilihan = '10' ] || [ $pilihan = '10' ]
then
git clone https://github.com/B4tak/T-FF
cd T-FF
python2 T-FF.py
fi

if [ $pilihan = '11' ] || [ $pilihan = '11' ]
then
git clone https://github.com/DarknessCyberTeam/B4J1N64Nv5

cd B4J1N64Nv5

sh B4J1N64N.sh
fi

if [ $pilihan = '12' ] || [ $pilihan = '12' ]
then
git clone https://github.com/dotfighter/torshammer.git
cd torshammer
python2 torshammer.py
fi

if [ $pilihan = '13' ] || [ $pilihan = '13' ]
then
git clone https://github.com/albertoanggi/xl-py
pip install requirements.txt
chmod +x app.py
python2 app.py
fi

if [ $pilihan = '14' ] || [ $pilihan = '14' ]
then
git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv4
cd TOOLSINSTALLERv4
sh TUANB4DUT..sh
fi

if [ $pilihan = '15' ] || [ $pilihan = '15' ]
then
git clone http://github.com/ciku370/OSIF
cd OSIF
python2 osif.py
fi

if [ $pilihan = '16' ] || [ $pilihan = '16' ]
then
git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv3
cd TOOLSINSTALLERv3
chmod +x TUANB4DUT.sh
sh TUANB4DUT.sh
fi

if [ $pilihan = '17' ] || [ $pilihan = '17' ]
then
git clone http://github.com/pirmansx/mbf
cd mbf
python2 mbf.py
fi

if [ $pilihan = '18' ] || [ $pilihan = '18' ]
then
git clone https://github.com/R133F/Trojans
cd Trojans
python2 trojans.py
fi

if [ $pilihan = '19' ] || [ $pilihan = '19' ]
then
git clone https://github.com/B4N954N2-ID/SpamWa
cd SpamWa
python2 spam-wa.py
fi

if [ $pilihan = '20' ] || [ $pilihan = '20' ]
then
echo '[•] sedang download cvk tunggu aja [•]' | lolcat
sleep 1
clear
apt update && apt upgrade
pkg update && pkg upgrade
pkg install git python2
pkg install python nano
pkg install gem
pkg install lolcat
pkg install ruby
pkg install mechanize requests
pip2 install mechanize requests
pkg install php bash
pip install mechanize requests
pkg install toilet figlet
sleep 1
echo "\033[32;1m[√] git done       [√]"
echo "\033[32;1m[√] python done    [√]"
echo '\033[32;1m[√] nano done      [√]'
echo '\033[32;1m[√] gem done       [√]'
echo '\033[32;1m[√] ruby done      [√]'
echo '\033[32;1m[√] mechanize done [√]'
echo '\033[32;1m[√] requests done  [√]'
echo '\033[32;1m[√] php done       [√]'
echo '\033[32;1m[√] bash done      [√]'
echo '\033[32;1m[√] toilet done    [√]'
echo '\033[32;1m[√] figlet done    [√]'
echo '\033[32;1m[√] lolcat done    [√]'
sleep 1
echo [#] install bahan sudah selesai cvk [√] | lolcat
sleep 1
echo [#] lho dah bisa pakai sekarang     [√] | lolcat
sleep 1
echo [#] ingat jangan di salah gunakan   [√] | lolcat
sh miniscript.sh
fi

if [ $pilihan = '00' ] || [ $pilihan = '00' ]
then
clear
echo "terima kasih telah menggunakan TOOLS ini" | lolcat
sleep 1
echo "sampai jumpa lain waktu see you next time" | lolcat
sleep 1
echo "tunggu versi berikutnya" | lolcat
sleep 1
figlet 'Mr.Boy 65' | lolcat
sleep 1
clear && exit
fi
